### ISSUE TITLE
[FR]: Explicit terms agreement

### ISSUE THREAD

**Issue by Huskydog9988** [waldo-vision/waldo#102]
### General Idea

Currently on the submission, review, and sign in page there is no explicit way for the user to agree to the terms, there is only an implicit agreement. Therefor, there **must** be a checkbox for the user to click to signal they agree to the TOS and Privacy Policy.  This checkbox would be on the sign in / sign up page, thus meaning that we likely don't need the additional notices on the submission and review page because the user must be authed to access these paged and you shouldn't be able to signup withoit agreeing.

implementation details:
There should be checks client and server side that the user agreed to the terms. The client side check just prevents them from sending, and the serverside check is just a flag in the json object.

### Problem

-

### Proper Description

-

### Any Alternatives?

None

### Additional context

-

**Comment by ceriddenn** [comment]
legal/login-checkbox (auth page) https://github.com/waldo-vision/waldo/commit/86a5aef622db561c885be4f287092cbd12829358
