### ISSUE TITLE
Create Cheating Label option in video submission page

### ISSUE THREAD

**Issue by jaredb1011** [waldo-vision/waldo#104]
Add option to label a submitted clip as 'Aimbot' or 'No Cheats' when a Trusted User (or higher privileged role) is submitting a clip.

This option should not be visible to standard users.

I'm imagining a dropdown list item where a user can select from the options to allow us to expand the types of cheats that can be labelled in the future.

**Comment by jaredb1011** [comment]
Will also need to add a field to the database to store the selected label. Call it CHEAT_TYPE or something like that.

**Comment by Huskydog9988** [comment]
Also see #103 for more info
