### ISSUE TITLE
[Bug]: Cannot setup Database

### ISSUE THREAD

**Issue by dukeluke** [waldo-vision/waldo#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hy i use debian 11 in a proxmox VM and try to get through the install Instructions here: [https://docs.waldo.vision/en/getting-started/](url)
When I run the command `yarn turbo run db:push` I get this output:
```bash
$`yarn turbo run db:push
• Packages in scope: backend, database, desktop, docs, eslint-config-custom, tsconfig, web
• Running db:push in 7 packages
• Remote caching disabled
database:db:push: cache bypass, force executing 60ab0451ae0ca164
database:db:push: Prisma schema loaded from prisma/schema.prisma
database:db:push: Datasource "db": CockroachDB database
database:db:push: 
database:db:push: Error: Prisma schema validation - (get-config wasm)
database:db:push: Error code: P1012
database:db:push: error: Environment variable not found: DATABASE_URL.
database:db:push:   -->  schema.prisma:10
database:db:push:    | 
database:db:push:  9 |   provider = "cockroachdb"
database:db:push: 10 |   url      = env("DATABASE_URL")
database:db:push:    | 
database:db:push: 
database:db:push: Validation Error Count: 1
database:db:push: [Context: getConfig]
database:db:push: 
database:db:push: Prisma CLI Version : 4.10.1
database:db:push: ERROR: command finished with error: command (/opt/waldo/packages/database) yarn run db:push exited (1)
command (/opt/waldo/packages/database) yarn run db:push exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.521s 

 ERROR  run failed: command  exited (1)
```

It says Environment Variable not found but i set the Environment Variable as in the instructions.

my .env file from /opt/waldo/apps/web:

```
# make sure to update the turbo.json

DISCORD_CLIENT_ID=example
DISCORD_CLIENT_SECRET=example

# google api
GOOGLE_CLIENT_ID=example
GOOGLE_CLIENT_SECRET=example
YOUTUBE_API_KEY=example

GITHUB_CLIENT_ID="myclientID"
GITHUB_CLIENT_SECRET="mysecretkey"

BTLNET_CLIENT_ID=example
BTLNET_CLIENT_SECRET=example

TWITCH_CLIENT_ID=example
TWITCH_CLIENT_SECRET=example

FB_CLIENT_ID=example
FB_CLIENT_SECRET=example

# cloudflare
CLOUDFLARE_TURNSTILE_SECRET=example
NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY=example

# database
DATABASE_URL="postgresql://root@localhost:26257?sslmode=disable"

# next auth
NEXTAUTH_URL=example
NEXTAUTH_SECRET=example
```

I tried to put "postgresql" in the /opt/waldo/packages/database/prisma/schema.prisma file with the same result.
How can i set the database variable correctly. Can I use my existing mysql database? And how?

### Steps To Reproduce

run 
`yarn turbo run db:push`

### Project

Website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dukeluke** [comment]
I got it with rename /opt/waldo/packages/database/.env.example to .env and put 
`DATABASE_URL="postgresql://root@localhost:26257?sslmode=disable"`
in there

**Comment by Huskydog9988** [comment]
Ok thanks for confirming that, I'll add that to the docs soon.

**Comment by dukeluke** [comment]
> From the looks of it you didn't set the env var in `packages/database`. (This is the env var used for pushing the schema to the database.) Seems like the documentation is missing this so I'll leave this issue open until we get that added, and you confirm this solve it.

According to setting up page the env file is located in apps/web/.env.example

**Comment by Huskydog9988** [comment]
Unfortunately prisma needs another in that workspace due to how we reuse that package.
