### ISSUE TITLE
[FR]: Hardcode admin IDs

### ISSUE THREAD

**Issue by Huskydog9988** [waldo-vision/waldo#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### General Idea

Add rican and homeless’s discord ids into next auth so that upon sign in they are automatically given the admin role.

### Problem

We need a better way to seed admins

### Projects

Website

### Any Alternatives?

Raw sql, which I’d rather not

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ceriddenn** [comment]
Done.
