### ISSUE TITLE
BACKEND: Check if user is in guild endpoint --ceri are we still implementing a guild check?

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#16]

**Comment by b3kN** [comment]
What is the status of this task? I think this was created and updated before deciding against the guild check, but I need validation.

@ceriddenn Can this task be removed, was it merged, or is it still WIP?

**Comment by ceriddenn** [comment]
I believe this is correct. We aren’t implementing the guild check anymore.

**Comment by b3kN** [comment]
Okay, thank you for that information & working on that initially. I know things have been up in the air recently, but I appreciate your flexibility!

**Comment by ceriddenn** [comment]
Yep its fine! Now that we are switching to multi-provider authentication, this endpoint is pretty much going to be useless

**Comment by b3kN** [comment]
Thanks for the updates. Closing this task based on the details above.
