### ISSUE TITLE
[Bug]: Sign in/Connecting Battle.net account fails

### ISSUE THREAD

**Issue by JeremieGGs** [waldo-vision/waldo#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to sign in or connect with battle.net does not work.

### Steps To Reproduce

1. Access https://waldo.vision/auth/login
2. Click on BattleNET
3. Check the box "I agree to the Terms of Service and Privacy Policy."
4. Click Connect button
5. Click Continue -> redirects successfully to https://waldo.vision/api/auth/signin?error=OAuthSignin
6. Click "Sign in with Battle.net" -> button presses -> page appears to reload -> loop

### Projects

Website

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Huskydog9988** [comment]
Thanks for the report, this is a know issue, and we are working on it

**Comment by arthur-rl** [comment]
Fixed in #189
