### ISSUE TITLE
API: Validate the tables and schema for MVP

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#19]
The objective of this task is to create and validate the schemas projected for the MVP.

- [x] Accounts Table (?)
- [x] Users Table/Schema
- [x] Footage Table/Schema
- [x] Voting Table/Schema
- [x] Session Table/Schema (?)

**Comment by ceriddenn** [comment]
The session, accounts and user tables are all for next auth. We have added custom relations to them to interact with our models.

**Comment by b3kN** [comment]
Excellent, I grabbed these details based on the Prisma Schema :) This task should be used to clarify these details as well as plan out the models and setting this expectations early on. I'll see to getting an updated running document for more granular details.

**Comment by ceriddenn** [comment]
Sounds good
