### ISSUE TITLE
API: Update POST to store available footage format details

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#20]
Update schemas to store details about the available formats for the YouTube video
Store available formats and desired video details into database

- [ ] Get available formats from YTDL
- [ ] List available formats, statistics, and ratings for criteria
- [ ] Validate legit YT video with acceptable footage criteria (eligible for download/processing)

**Comment by ceriddenn** [comment]
I’m guessing we can get rid of this issue?

**Comment by Huskydog9988** [comment]
did we complete this?
