### ISSUE TITLE
API: Finalize API Rate limiting

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#21]
R&D: Find and implement best lightweight option for rate limiting on Next API system

- [ ] Research ideal rate limiting system for Next API
- [ ] Implement rate limiting framework for Next API

**Comment by ceriddenn** [comment]
I'll keep adding options here as I look for more
1. https://www.npmjs.com/package/lru-cache SOURCE Example: https://nextjs-rate-limit.vercel.app/
There are really not a lot of options if you search, we could use an express library but idk how viable it would be.

**Comment by Huskydog9988** [comment]
This made the rounds a bit ago, and we **may** be able to use our own redis server instead of their paid platform https://github.com/upstash/ratelimit. If so, it seems like a great option for scalability.

**Comment by winegard-developer** [comment]
I haven't looked at this rate limiter, but I did see several concepts created with Redis that looked promising. We'll need something along these lines for the MVP, but feel free to tag in any additional frameworks/opportunities.

**Comment by ceriddenn** [comment]
Decided on https://github.com/microlinkhq/async-ratelimiter. Was updated within the last month and works w a redis server.
