### ISSUE TITLE
[FR]: No default game selection

### ISSUE THREAD

**Issue by Huskydog9988** [waldo-vision/waldo#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### General Idea

Force users to choose which game they are submitting for.

### Problem

People don't properly label their submissions

### Projects

Website

### Any Alternatives?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bensikrac** [comment]
Implemented with #276
