### ISSUE TITLE
CI/CD: Implement GitHub Actions

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#24]
- [x] Implement docs gh-pages deploy
- [x] need linting
- [x] should also lint styles too

**Comment by nicobleiler** [comment]
What kind of Pipelines are these supposed to be?

**Comment by Huskydog9988** [comment]
Within ci, can we consider adding code scanning, as well as dependabot?

**Comment by cgund98** [comment]
Is there anything else we need to implement regarding this issue?

**Comment by Huskydog9988** [comment]
not exactly, we need testing, but thats probably worth its own issue
