### ISSUE TITLE
Admin / Mod cannot delete gameplay

### ISSUE THREAD

**Issue by jaredb1011** [waldo-vision/waldo#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Moderators / Admins are unable to delete gameplay using the admin dashboard.

You can select the delete action on a submission, and the process seems to complete, but the submission remains in the list of submissions, and does not actually get removed.

### Steps To Reproduce

Go to admin dashboard
Go to gameplay tab
Select a gameplay submission from the table of submission
Select the actions dropdown and choose 'Delete Gameplay'

### Projects

Website

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ceriddenn** [comment]
Um so this is not the issue… the list of gameplay items will update EVEN without a requery. There is an actual endpoint error preventing gameplay deletion. Please make sure you understand the whole issue and debug it before we attempt to fix it.

**Comment by jaredb1011** [comment]
@ceriddenn so this should be completed now, right?

**Comment by ceriddenn** [comment]
This was fixed a while ago so yeah @jaredb1011.
