### ISSUE TITLE
CI/CD: Implement Kubernetes deployments

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#25]
R&D: Validate kubernetes deployments and public accessibility on staging server

- [x] Implement Kubernetes cluster on staging server
- [x] Create docker images for each app (web, desktop)
- [x] Upload images to repository for cluster usage
- [x] Align cluster to use docker images for each project container

see infra project board for updated info on this task

**Comment by Huskydog9988** [comment]
completed
