### ISSUE TITLE
API: Create endpoint to blacklist user

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#26]
Create endpoint to ban a specific user
DELETE /user/:uuid (?)

- [ ] For the time being this should update the banned boolean in schema

**Comment by ceriddenn** [comment]
I think we will need an endpoint for banning users and then an endpoint for deleting them

**Comment by ceriddenn** [comment]
Also, I think we should wait on adding things or updating the back-end until it has been migrated to next. We don't want to write code when it needs to be converted anyways.... unless someone is up for that.

**Comment by b3kN** [comment]
I agree, the schema and general endpoints should be established before anything; I will add some dependency on the current API items. 

This should be the banning endpoint, but I didn't clarify well. I specified a `DELETE` endpoint, but this could be re-targeted as needed

**Comment by ceriddenn** [comment]
Yup, sounds good!

**Comment by ceriddenn** [comment]
Done, tested it last night
