### ISSUE TITLE
UI: Develop Submission Form Mockup

### ISSUE THREAD

**Issue by b3kN** [waldo-vision/waldo#33]
It is intended that the front-end parts would be hosted on the existing domain through the cloudflare instance. This way we can maintain styling accordingly and would be a separate page on the existing tailwind/vite site.

Using the preferred framework by the front end team, the submission form should require the Discord username, Discord ID, and a valid YouTube video URL. In addition to these factors, there should be some kind of human authentication input (ReCAPTCHA or Turnstile).

An additional possibility for authentication would be to use a Discord OAuth application on the web form.
https://discordjs.guide/oauth2/#a-quick-example

**Comment by b3kN** [comment]
This was initially created before recent accomplishments, but can be aligned for the UI on the submission form specifically. Some of this may have already been implemented with the upload views.

**Comment by ceriddenn** [comment]
Are we planning on impl recaptcha or turnstile?

**Comment by Huskydog9988** [comment]
I think we leaned towards turnstile when this was discussed previously but idk if anything's changed

**Comment by winegard-developer** [comment]
Good questions. The site was using Cloudflare pages originally, but the specifications have changed slightly with the web application being hosted in tandem with the backend API. In the end, we mostly need some kind of human-verification processing...

Both ReCaptcha v3 & Turnstile have implicit validation which should be sufficient

**Comment by b3kN** [comment]
Good questions. The site was using Cloudflare pages originally, but the specifications have changed slightly with the web application being hosted in tandem with the backend API. In the end, we mostly need some kind of human-verification processing...

I believe we are already using Google Cloud, so maybe ReCaptcha makes sense here

Both ReCaptcha v3 & Turnstile have implicit validation which should be sufficient.

[Turnstile](https://developers.cloudflare.com/turnstile/)
[ReCaptcha v3](https://developers.google.com/recaptcha/docs/v3)
