### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HideInDust** [waldo-vision/waldo#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened! please help me!

![image](https://github.com/waldo-vision/waldo/assets/23160090/25551fbe-1ee3-44d0-828b-c083db4b5415)

### Steps To Reproduce

1. yarn workspace web dev
2. open http://localhost:3000 and click [Submissions]
3. then i see this error

### Projects

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ceriddenn** [comment]
Have you generated the prisma client yet?
