### ISSUE TITLE
[Bug]: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.

### ISSUE THREAD

**Issue by HideInDust** [waldo-vision/waldo#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened:
![image](https://github.com/waldo-vision/waldo/assets/23160090/3c35aa76-2c39-4fb5-9af3-8c0bc69357c6)

but my .env file is correct:
![image](https://github.com/waldo-vision/waldo/assets/23160090/b12bfd3a-a20f-4cf6-8ca7-ef80c448d6c0)
![image](https://github.com/waldo-vision/waldo/assets/23160090/063c8ab9-afad-4e80-b25d-02cf6bf0b993)

### Steps To Reproduce

no

### Projects

Website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Huskydog9988** [comment]
What did you do to solve the issue? From the looks of things the uris were already correct.
