### ISSUE TITLE
[Bug]: I did all things according to the guide，but the website can't work！

### ISSUE THREAD

**Issue by HideInDust** [waldo-vision/waldo#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1）the video can't be uploaded：
![image](https://github.com/waldo-vision/waldo/assets/23160090/22ca576c-9193-48d7-9544-306d8c4a80be)
2）the review gameplay page is forver loading:
![image](https://github.com/waldo-vision/waldo/assets/23160090/f4148b81-480c-4338-9ada-0edb56e6f991)
3）the server error:
![image](https://github.com/waldo-vision/waldo/assets/23160090/43e90f3c-fe6a-4e5f-8da0-424f2915327f)

### Steps To Reproduce

I do all things follow the guide document, then these errors appeared.

### Projects

Website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HideInDust** [comment]
I check the db, find the public."WaldoPage" is exist, but the other data's  Replication Size is 0kb, why？I have already run this:
`yarn turbo db:generate
yarn turbo run db:push`
and run sucess.
![image](https://github.com/waldo-vision/waldo/assets/23160090/bfb2ff5c-e877-4f66-aa33-8deb3e256ced)

**Comment by Huskydog9988** [comment]
I think I got it. Assuming you don't care if you loose any data, I'd recommend running `db:init`, since that also calls the seeding cmd, or if you'd prefer to retain whatever you have in the db, you should run `db:seed`. See the [database package.json](https://github.com/waldo-vision/waldo/blob/staging/packages/database/package.json) for more details if you want some other options too. 

If you wanna try and get prisma to always seed when one of those cmds is run, I'd appreciate the pr to `v2/main`.

**Comment by HideInDust** [comment]
> 
I have tried according to your reply，the result is：
![image](https://github.com/waldo-vision/waldo/assets/23160090/50f65403-56af-4cd1-be50-c665006c49b7)

But the web still  can't work, I still can't upload videos and  review gameplay page like this:
![image](https://github.com/waldo-vision/waldo/assets/23160090/3f7aa66b-4b75-47d2-8b31-1b1dd0e4833e)

and the database's replication size is still 0kb:
![image](https://github.com/waldo-vision/waldo/assets/23160090/f75a55e5-5e28-476c-9740-48612d3d58c0)

**Comment by ceriddenn** [comment]
Can you send a screenshot of the dev tools console log please? Take a screenshot of the errors that pop up.

**Comment by ceriddenn** [comment]
I believe that has to do with turnstile though so make sure you put the demo (dev test) keys from cloudflare's turnstile development FAQ in your ENV.

Here's a page to get you started:
[](https://developers.cloudflare.com/turnstile/reference/testing/ )

**Comment by HideInDust** [comment]
Thanks, I have tried according to your reply, after adding the keys from cloudflare, I upload videos successful, but there are still some problem:
1) TRPC failed. (I have added other logs and hope they can help you locate the problem) 
![image](https://github.com/waldo-vision/waldo/assets/23160090/3d3a3e19-f826-435e-b619-76de81522949)

2）the "Review Gameplay" pade shows "no more videos to show"
![image](https://github.com/waldo-vision/waldo/assets/23160090/ebb94fdb-cbb5-48d0-a983-07c606213169)

3) I run the db:push:fdl,  db:seed, but the database is still empty, there are console logs:

![image](https://github.com/waldo-vision/waldo/assets/23160090/216baa26-60e9-486e-aeba-c1148478da59)
![image](https://github.com/waldo-vision/waldo/assets/23160090/181e9e9e-9bef-4195-a877-dbcf7a6839e1)
![image](https://github.com/waldo-vision/waldo/assets/23160090/c67190af-cc72-4296-b458-ba13db0525ed)
![image](https://github.com/waldo-vision/waldo/assets/23160090/a66e156b-5eec-4cf2-bf6b-ccd716046e3f)
![image](https://github.com/waldo-vision/waldo/assets/23160090/3aa94ab4-9eb0-43ba-affd-946fde7667fb)

**Comment by ceriddenn** [comment]
Okay 1, the error says Not_Found on the review page query endpoint. That means you haven't uploaded any videos. This could also occur if you have already reviewed those videos... if you have they won't ever show up again as that's how the small algorithm we built works. I believe it also won't show videos that you uploaded on the review page if you (the owner) are logged in, it will show your videos to other users though.

**Comment by HideInDust** [comment]
ok，thank you for your help！

**Comment by Huskydog9988** [comment]
Did that solve the issue?

**Comment by HideInDust** [comment]
Yes, the website run successfully, but after uploading the video, I can't see any other information about it，such as prediction results and the deep learning model's information.

**Comment by ceriddenn** [comment]
Okay closing because issue was solved...
