### ISSUE TITLE
[Bug]: www.waldo.vision returns 404

### ISSUE THREAD

**Issue by developomp** [waldo-vision/waldo#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Connecting to www.waldo.vision always returns 404 while [waldo.vision](https://waldo.vision) is working just fine. The former link is used in at least one of waldo-vision repo (https://github.com/waldo-vision/optical.flow.demo), so I think this is something that's worth fixing.

### Steps To Reproduce

1. Visit www.waldo.vision

### Projects

Website

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Huskydog9988** [comment]
just resolved this, thanks for bringing it up
