### ISSUE TITLE
Remaining tasks to complete for v1

### ISSUE THREAD

**Issue by ceriddenn** [waldo-vision/waldo#54]
### Backend
- [x] Make sure api security is up to snuff
- [x] nextjs security headers
	- [x] csp
	- [x] referance nextjs's guide
	- [x] need to apply 'unsafe-eval' only when not in prod
- [x] Fix review page re-render bug
- [x] k8s cluster
	- [x] vault
	- [x] website
		- [x] docker image
		- [x] helm chart
	- [x] docs
		- [x] docker image
		- [x] helm chart

### docs
- [x] robots.txt
- [x] 404 page
- [ ] #148  includes
   - [ ] #145 
   - [ ] #99 
   - [ ] #146 

### Frontend
- styling: terms of service, snackbar, disabled option and a scroll viewbox issue on chrome based browser 
all on login page
- [x] robots.txt
- [x] Context migration
    - [x] isLoading for each page working
    - [x] Session migrated
- [x] #58
   - [x] Account 
   - [x] Review
   - [x] Upload
   - [x] Maintenance
- [x] Finish Admin dash design 
- [x] Gameplay @ceriddenn 
- [x] Legal (rican)? 23/12/2022
-[ ] add pages for each legal document.
	- [x] update tos link in footer
	- [x] add privacy policy
	- [x] add cookie policy
	- [x] add code of conduct?
- [x] Min Legal required for comm testing
- [x] Update acc page (gameplay) responsiveness
- [x] User Panel search and filter logic @ceriddenn 
- [x] Fix any build errors (next build)
(feel free to add any other tasks here)
- [x] make roles an enum again
- [x] review 
	- [x] should use turnstile here too
	- [x] getReviewItems currently exposes the FULL user schema this INCLUDES THE USER EMAIL!!
	- [x] page doesn't consistentlyload
- [x] comeplete 'resolved' items in #61 
	- there are a number with the comment `will solve later`, these should be addresses in new prs
- [x] #35 
- [x] make turnstile site key an env var
- [x] Add a design to the new Finished component that renders if the review page no longer receives gameplay docs for the user. 
- [x] dashboard
	- [x] handle apply functions on the pages use the change arg, but its not clear what the number it contains repersents
	(just going to add comments that explains what each # change does -ceri)
	- [x] remove typecasting in the form of `as`, defeats the purpose of ts

**Comment by tsundDEV** [comment]
**Bugs & Issues:**
- [ ] isLoading issue with site disabling on upload and review page. 
- [ ] Site page responsiveness

**Missing features:**
- [ ] Account Disabling
- [ ] Gameplay Panel
- [ ] User Panel search and filter logic

**Reviewing:**
- [ ]  All Pages
- [ ] Fix types


**_To be updated_**

**Comment by Huskydog9988** [comment]
see #99 for remaing task from here

**Comment by tsundDEV** [comment]
Reopened for #99 and #145
