### ISSUE TITLE
getYtVidDataFromId endpoint is ripe for abuse

### ISSUE THREAD

**Issue by Huskydog9988** [waldo-vision/waldo#96]
### General Idea

The getYtVidDataFromId endpoint should be removed and should instead be an internal function used to seed data into the nessicary endpoints.

### Problem

The getYtVidDataFromId can be abused by malicious actors to spam the yt api using our key, potentially getting us ratelimited.

### Proper Description

_

### Any Alternatives?

No, this is nessicary task

### Additional context

_

**Comment by tsundDEV** [comment]
#129 Fixed in merge
